version: '3.8'
services:
  postgres-test:
    image: postgres:15.5 # This matches our RDS instance postgres version
    restart: always
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: local
    ports:
      - 5432:5432
